// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcTransactionNoticeService.proto

package org.springrain.rpc.grpcauto;

public interface NoticeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NoticeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>int32 result = 2;</code>
   */
  int getResult();
}
