// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcTransactionNoticeService.proto

package org.springrain.rpc.grpcauto;

public interface NoticeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:NoticeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string txId = 1;</code>
   */
  java.lang.String getTxId();
  /**
   * <code>string txId = 1;</code>
   */
  com.google.protobuf.ByteString
      getTxIdBytes();

  /**
   * <code>string txGroupId = 2;</code>
   */
  java.lang.String getTxGroupId();
  /**
   * <code>string txGroupId = 2;</code>
   */
  com.google.protobuf.ByteString
      getTxGroupIdBytes();

  /**
   * <code>int32 operation = 3;</code>
   */
  int getOperation();
}
