// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: grpcTransactionNoticeService.proto

package org.springrain.rpc.grpcauto;

/**
 * <pre>
 * 定义通用的 Grpc 事务通知 请求体
 * </pre>
 *
 * Protobuf type {@code NoticeRequest}
 */
public  final class NoticeRequest extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:NoticeRequest)
    NoticeRequestOrBuilder {
private static final long serialVersionUID = 0L;
  // Use NoticeRequest.newBuilder() to construct.
  private NoticeRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private NoticeRequest() {
    txId_ = "";
    txGroupId_ = "";
    operation_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private NoticeRequest(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();

            txId_ = s;
            break;
          }
          case 18: {
            java.lang.String s = input.readStringRequireUtf8();

            txGroupId_ = s;
            break;
          }
          case 24: {

            operation_ = input.readInt32();
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return org.springrain.rpc.grpcauto.GrpcAutoCreateTransactionNoticeService.internal_static_NoticeRequest_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return org.springrain.rpc.grpcauto.GrpcAutoCreateTransactionNoticeService.internal_static_NoticeRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            org.springrain.rpc.grpcauto.NoticeRequest.class, org.springrain.rpc.grpcauto.NoticeRequest.Builder.class);
  }

  public static final int TXID_FIELD_NUMBER = 1;
  private volatile java.lang.Object txId_;
  /**
   * <code>string txId = 1;</code>
   */
  public java.lang.String getTxId() {
    java.lang.Object ref = txId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txId_ = s;
      return s;
    }
  }
  /**
   * <code>string txId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getTxIdBytes() {
    java.lang.Object ref = txId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int TXGROUPID_FIELD_NUMBER = 2;
  private volatile java.lang.Object txGroupId_;
  /**
   * <code>string txGroupId = 2;</code>
   */
  public java.lang.String getTxGroupId() {
    java.lang.Object ref = txGroupId_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      txGroupId_ = s;
      return s;
    }
  }
  /**
   * <code>string txGroupId = 2;</code>
   */
  public com.google.protobuf.ByteString
      getTxGroupIdBytes() {
    java.lang.Object ref = txGroupId_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      txGroupId_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int OPERATION_FIELD_NUMBER = 3;
  private int operation_;
  /**
   * <code>int32 operation = 3;</code>
   */
  public int getOperation() {
    return operation_;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!getTxIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, txId_);
    }
    if (!getTxGroupIdBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 2, txGroupId_);
    }
    if (operation_ != 0) {
      output.writeInt32(3, operation_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (!getTxIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, txId_);
    }
    if (!getTxGroupIdBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, txGroupId_);
    }
    if (operation_ != 0) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt32Size(3, operation_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof org.springrain.rpc.grpcauto.NoticeRequest)) {
      return super.equals(obj);
    }
    org.springrain.rpc.grpcauto.NoticeRequest other = (org.springrain.rpc.grpcauto.NoticeRequest) obj;

    boolean result = true;
    result = result && getTxId()
        .equals(other.getTxId());
    result = result && getTxGroupId()
        .equals(other.getTxGroupId());
    result = result && (getOperation()
        == other.getOperation());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + TXID_FIELD_NUMBER;
    hash = (53 * hash) + getTxId().hashCode();
    hash = (37 * hash) + TXGROUPID_FIELD_NUMBER;
    hash = (53 * hash) + getTxGroupId().hashCode();
    hash = (37 * hash) + OPERATION_FIELD_NUMBER;
    hash = (53 * hash) + getOperation();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static org.springrain.rpc.grpcauto.NoticeRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(org.springrain.rpc.grpcauto.NoticeRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * 定义通用的 Grpc 事务通知 请求体
   * </pre>
   *
   * Protobuf type {@code NoticeRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:NoticeRequest)
      org.springrain.rpc.grpcauto.NoticeRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.springrain.rpc.grpcauto.GrpcAutoCreateTransactionNoticeService.internal_static_NoticeRequest_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.springrain.rpc.grpcauto.GrpcAutoCreateTransactionNoticeService.internal_static_NoticeRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.springrain.rpc.grpcauto.NoticeRequest.class, org.springrain.rpc.grpcauto.NoticeRequest.Builder.class);
    }

    // Construct using com.mzywx.rpc.grpcauto.NoticeRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      txId_ = "";

      txGroupId_ = "";

      operation_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return org.springrain.rpc.grpcauto.GrpcAutoCreateTransactionNoticeService.internal_static_NoticeRequest_descriptor;
    }

    public org.springrain.rpc.grpcauto.NoticeRequest getDefaultInstanceForType() {
      return org.springrain.rpc.grpcauto.NoticeRequest.getDefaultInstance();
    }

    public org.springrain.rpc.grpcauto.NoticeRequest build() {
      org.springrain.rpc.grpcauto.NoticeRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public org.springrain.rpc.grpcauto.NoticeRequest buildPartial() {
      org.springrain.rpc.grpcauto.NoticeRequest result = new org.springrain.rpc.grpcauto.NoticeRequest(this);
      result.txId_ = txId_;
      result.txGroupId_ = txGroupId_;
      result.operation_ = operation_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof org.springrain.rpc.grpcauto.NoticeRequest) {
        return mergeFrom((org.springrain.rpc.grpcauto.NoticeRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(org.springrain.rpc.grpcauto.NoticeRequest other) {
      if (other == org.springrain.rpc.grpcauto.NoticeRequest.getDefaultInstance()) return this;
      if (!other.getTxId().isEmpty()) {
        txId_ = other.txId_;
        onChanged();
      }
      if (!other.getTxGroupId().isEmpty()) {
        txGroupId_ = other.txGroupId_;
        onChanged();
      }
      if (other.getOperation() != 0) {
        setOperation(other.getOperation());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      org.springrain.rpc.grpcauto.NoticeRequest parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (org.springrain.rpc.grpcauto.NoticeRequest) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private java.lang.Object txId_ = "";
    /**
     * <code>string txId = 1;</code>
     */
    public java.lang.String getTxId() {
      java.lang.Object ref = txId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string txId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getTxIdBytes() {
      java.lang.Object ref = txId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txId = 1;</code>
     */
    public Builder setTxId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string txId = 1;</code>
     */
    public Builder clearTxId() {
      
      txId_ = getDefaultInstance().getTxId();
      onChanged();
      return this;
    }
    /**
     * <code>string txId = 1;</code>
     */
    public Builder setTxIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      txId_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object txGroupId_ = "";
    /**
     * <code>string txGroupId = 2;</code>
     */
    public java.lang.String getTxGroupId() {
      java.lang.Object ref = txGroupId_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        txGroupId_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string txGroupId = 2;</code>
     */
    public com.google.protobuf.ByteString
        getTxGroupIdBytes() {
      java.lang.Object ref = txGroupId_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        txGroupId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string txGroupId = 2;</code>
     */
    public Builder setTxGroupId(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      txGroupId_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string txGroupId = 2;</code>
     */
    public Builder clearTxGroupId() {
      
      txGroupId_ = getDefaultInstance().getTxGroupId();
      onChanged();
      return this;
    }
    /**
     * <code>string txGroupId = 2;</code>
     */
    public Builder setTxGroupIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      txGroupId_ = value;
      onChanged();
      return this;
    }

    private int operation_ ;
    /**
     * <code>int32 operation = 3;</code>
     */
    public int getOperation() {
      return operation_;
    }
    /**
     * <code>int32 operation = 3;</code>
     */
    public Builder setOperation(int value) {
      
      operation_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int32 operation = 3;</code>
     */
    public Builder clearOperation() {
      
      operation_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:NoticeRequest)
  }

  // @@protoc_insertion_point(class_scope:NoticeRequest)
  private static final org.springrain.rpc.grpcauto.NoticeRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new org.springrain.rpc.grpcauto.NoticeRequest();
  }

  public static org.springrain.rpc.grpcauto.NoticeRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<NoticeRequest>
      PARSER = new com.google.protobuf.AbstractParser<NoticeRequest>() {
    public NoticeRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new NoticeRequest(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<NoticeRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<NoticeRequest> getParserForType() {
    return PARSER;
  }

  public org.springrain.rpc.grpcauto.NoticeRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

